name: fitness
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.0.0+4
  path_provider: ^2.0.10
  floor: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.0
  build_runner: ^2.4.6

  # Recommended lints for better coding practices.
  flutter_lints: ^5.0.0

flutter:
  # Use material design icons and fonts.
  uses-material-design: true

  # Adding assets for exercises.
  assets:
    - assets/muscleGroup/chest.png
    - assets/muscleGroup/back.png
    - assets/muscleGroup/shoulders.png
    - assets/muscleGroup/hands.png
    - assets/muscleGroup/abs.png
    - assets/muscleGroup/legs.png
    - assets/exercise/press_bench.jpg

  # Optional: Custom fonts (add fonts here if needed in the future).
